### ISSUE TITLE
Invalid template variable "#label" fails due to: Formula is not a constructor

### ISSUE THREAD

**Issue by pgangwani** [hapijs/h2o2#114]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v12.3.1
* *module version with issue*: 9.0.1
* *last module version without issue*: 8.3.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?
1. Upgrading node to lts
2. upgraded hapi modules compatible 
3. webpack build
4. node start

```js

```

#### What was the result you got?
```
/Users/pgangaw/global-header-footer/node_modules/@hapi/h2o2/node_modules/@hapi/joi/lib/template.js:213
            throw err;
            ^

TypeError: Invalid template variable "#label" fails due to: Formula is not a constructor
    at module.exports.internals.Template._ref (/Users/pgangaw/global-header-footer/node_modules/@hapi/h2o2/node_modules/@hapi/joi/lib/template.js:209:27)
    at module.exports.internals.Template._parse (/Users/pgangaw/global-header-footer/node_modules/@hapi/h2o2/node_modules/@hapi/joi/lib/template.js:82:34)
    at new module.exports.internals.Template (/Users/pgangaw/global-header-footer/node_modules/@hapi/h2o2/node_modules/@hapi/joi/lib/template.js:42:14)
    at Object.exports.compile (/Users/pgangaw/global-header-footer/node_modules/@hapi/h2o2/node_modules/@hapi/joi/lib/messages.js:45:28)
    at Object.exports.merge (/Users/pgangaw/global-header-footer/node_modules/@hapi/h2o2/node_modules/@hapi/joi/lib/messages.js:117:24)
    at Object.exports.type (/Users/pgangaw/global-header-footer/node_modules/@hapi/h2o2/node_modules/@hapi/joi/lib/extend.js:24:29)
    at internals.Base.extend (/Users/pgangaw/global-header-footer/node_modules/@hapi/h2o2/node_modules/@hapi/joi/lib/base.js:434:23)
    at Object.<anonymous> (/Users/pgangaw/global-header-footer/node_modules/@hapi/h2o2/node_modules/@hapi/joi/lib/types/any.js:13:23)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
```
#### What result did you expect?
node server should start smoothly

**Comment by Marsup** [comment]
Looks like you've got a bad install, do you have a lock file messing things up ?
Can you show the result of `npm ls @hapi/formula` ?

**Comment by pgangwani** [comment]
@Marsup 

```
├─┬ @hapi/h2o2@9.0.1
│ └─┬ @hapi/joi@16.1.7 invalid
│   └── UNMET DEPENDENCY @hapi/formula@^1.2.0
└─┬ @hapi/joi@17.1.0
  └── @hapi/formula@2.0.0 

```

**Comment by Marsup** [comment]
I'm surprised it didn't help *you*, I mean it's all written right there :joy: 
h2o2 9.0.1 should have a joi 17 which in turn should have a formula 2. I don't know what you did but you have to reinstall your deps properly.

**Comment by pgangwani** [comment]
@Marsup hehe, yes I can relate your feeling.  😂
Bdw its resolved by deleting node_module & lock file and then ```yarn install``
