### ISSUE TITLE
Error when using mapUri

### ISSUE THREAD

**Issue by ro-ka** [hapijs/h2o2#38]
I register a simple proxy handler:

```js
  {
    method: 'GET',
    path: '/_api/{variables}',
    handler: {
      proxy: {
        passThrough: true,
        mapUri: (request, callback) => {
          callback(null, baseUri + request.params.variables);
        }
      }
    }
  }
```

This leads to the following error:

```sh
Debug: internal, implementation, error
    Error: Uncaught error: options.payload must be a string, a Buffer, or a Stream
    at Object.exports.assert (/Users/robert/Entwicklung/my-project/node_modules/hoek/lib/index.js:736:11)
    at internals.Client.request (/Users/robert/Entwicklung/my-project/node_modules/wreck/lib/index.js:75:10)
    at settings.mapUri (/Users/robert/Entwicklung/my-project/node_modules/h2o2/lib/index.js:140:19)
    at Object.mapUri (/Users/robert/Entwicklung/my-project/src/routes/api.js:21:11)
```

As far as I found out, `h2o2` creates an options object, but `wreck` requires it to not be an object. Is this intentional?

**Comment by ro-ka** [comment]
Can you give me some feedback? With this error Hapi > 9 is unusable for us.

**Comment by mtharrison** [comment]
Any chance you can provide a complete example showing this problem? One that we can run to confirm the behaviour?

**Comment by ro-ka** [comment]
I’ve reduced to a minimal example and found some things out. First, the test files to reproduce:

package.json
```json
{
  "name": "hapi-h2o2-error",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "good": "^7.0.1",
    "good-console": "^6.1.2",
    "good-squeeze": "^4.0.0",
    "h2o2": "^5.1.0",
    "hapi": "^13.5.0",
    "hapi-qs": "^1.1.1"
  }
}
```

The index.js:
```js
var Hapi = require('hapi');
var server = new Hapi.Server();

server.connection({host: 'localhost', port: 3000});

server.register([
  require('h2o2'),
  require('hapi-qs'),
  {
    register: require('good'),
    options: {
      reporters: {
        console: [{
          module: 'good-squeeze',
          name: 'Squeeze',
          args: [{log: '*', response: '*'}]
        }, {
          module: 'good-console'
        }, 'stdout']
      }
    }
  }
], (error) => {
  if (error) {
    throw error;
  }

  server.route([  {
    method: 'GET',
    path: '/test',
    handler: {
      proxy: {
        passThrough: true,
        mapUri: (request, callback) => {
          callback(null, 'https://api.github.com/users/ro-ka');
        }
      }
    }
  }]);
});

server.start(error => {
  if (error) {
    throw(error);
  }

  server.log('info', `Server running at: ${server.info.uri}`);
});
```

I installed `good` for logging. And I installed `hapi-qs` because we need it and it only breaks when this is installed.

Second thing that causes this error is this header: `Content-Type: application/x-www-form-urlencoded`. So when using `curl`, this is what happens:

```sh
~ – curl 'http://localhost:3000/test' -H 'Content-Type: application/x-www-form-urlencoded'
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

~ – curl 'http://localhost:3000/test'
{
  "login": "ro-ka",
  "id": 840022,
  "avatar_url": "https://avatars.githubusercontent.com/u/840022?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/ro-ka",
  …
}
```

So the error only occurs when the `hapi-qs` package is installed and the header set. Is it an error of this module or of the `hapi-qs` module?

**Comment by mtharrison** [comment]
It's a bug with that module. It shouldn't be parsing a payload on a route with payload parsing explicitly disabled.

**Comment by ro-ka** [comment]
Okay, will file the issue there. Reported here as the error occurred in this module.
