### ISSUE TITLE
https Error: tunneling socket could not be established, cause=socket hang up

### ISSUE THREAD

**Issue by panKt** [hapijs/h2o2#39]
I'm trying to implement forward proxy and it works ok for `http` requests, but for `https` it says:

```
Error: tunneling socket could not be established, cause=socket hang up
    at ClientRequest.onError (/Users/zak/dev/proxy/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnEnd (_http_client.js:344:9)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Here is an example of code (node 6). Just replace 
`const url   = 'http://www.example.com'`
with
`const url   = 'https://www.example.com'`
to see the error

``` javascript
const h2o2    = require('h2o2')
const Hapi    = require('hapi')
const request = require('request')

const server = new Hapi.Server()
server.connection({ host:'localhost', port:3001 })

server.register([{ register:h2o2 }], function(err) {
  server.start(function(err) {
    if (err) return console.error(err)
    console.log('started at', server.info.uri)
    fetchUsingThisProxy()
  })
})

server.route({
  method  : '*',
  path    : '/fwd/{path*}',
  handler : (req, res) => {
    res('FORWAREDED')
  }
})

server.route({
  method  : '*',
  path    : '/{path*}',
  handler : {
    proxy : {
      passThrough    : true,
      acceptEncoding : false,
      timeout        : 15000,
      redirects      : 10,
      uri            : 'http://localhost:3001/fwd',
      onResponse (err, res, request, reply, settings, ttl) {
        reply(res)
      }
    }
  }
})

function fetchUsingThisProxy() {
  const url   = 'http://www.example.com'
  const proxy = server.info.uri
  const opts  = { url, proxy }

  return request(opts, (err, response, body) => {
    if (err) throw err
    console.log(body)
  })
}
```

**Comment by spanditcaa** [comment]
The error in the example above is expected, and returned because request is attempting to establish a socket connection to https://www.example.com and there is nothing answering on port 443.  H2o2 is not a forward proxy - in your example request is not retrieving content from http://www.example.com so it is not 'working' for this scenario either.

See https://github.com/request/request#proxies for how request establishes its tunneling connections.
